server:
  port: 8089

spring:
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: mongodbDemo
      username: root
      password: root
  redis:
    database: 1
    host: 127.0.0.1
    open: true # 是否开启redis缓存  true开启   false关闭
    port: 6379
    timeout: 5000s  # 连接超时时长（毫秒）
    lettuce:
      pool:
        max-active: 1000 #连接池最大连接数（使用负值表示没有限制）
        max-idle: 1000  #连接池中的最大空闲连接
        max-wait: -1s #连接池最大阻塞等待时间（使用负值表示没有限制)
        min-idle: 0  #连接池中的最小空闲连接
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

elasticsearch:
  #集群地址，多个用，隔开
  host: 127.0.0.1:9200,127.0.0.1:9201,127.0.0.1:9202
  #最大线程数并发数量
  maxConnTotal: 100
  maxConnPerRoute: 100

fdfs:
  pool:
    max-total: 1000
    max-total-per-key: 1000
    max-wait-millis: 3000
  tracker-list:
    - 127.0.0.1:22122
  groupMap:
    group1: 127.0.0.1
    #group2: 44.87.9.2001